services:
  - type: web
    name: climate-intel-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: climate_intel
      - key: NEWSDATA_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.16
